In [1]:
import sys
import numpy as np
import time
import matplotlib.pyplot as plt
from scipy import interpolate 
import qutip as qt
sys.path.append(r'C:\Chuji\Code_and_Data\SourceCode\Labber_Drivers\Drivers\MultiQubit_PulseGenerator_Custom')

In [2]:
def Lt(jump_operator,density):
    return jump_operator*density*jump_operator.dag()-0.5*jump_operator.dag()*jump_operator*density - 0.5*density*jump_operator.dag()*jump_operator

In [165]:
def TimeEvolution(H,gamma,jump_operator,rho,dt):
    points=10000
    for i in range(points):
        rho = rho - 1j*(H*rho-rho*H)*dt/points + Lt(gamma*jump_operator,rho)*dt/points
        rho = rho/rho.norm()
    return rho

In [217]:
TimeEvolution(0.5*qt.sigmax()*0e6*2*np.pi,np.sqrt(1e6),qt.destroy(2), qt.basis(2,0)*qt.basis(2,0).dag(),dt=50e-9)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [223]:
A = np.zeros([5,5])
A[2,1]=1
jump_operator = qt.Qobj(A)
jump_operator

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [224]:
0.5*qt.Qobj([[0,1,0,0,0],[1,0,0,0,0],[0,0,0,1,0],[0,0,1,0,0],[0,0,0,0,1]])

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.5 0.  0.  0. ]
 [0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.5]]

In [225]:
Error = []
Ref_Error=[]
for state in Total_60_extend:
    density_mat = qt.Qobj(state)*qt.Qobj(state).dag()
    H_SWAP = 0.5*qt.Qobj([[0,1,0,0,0],[1,0,0,0,0],[0,0,0,1,0],[0,0,1,0,0],[0,0,0,0,1]])*10e6*2*np.pi
    ideal_state = TimeEvolution(H_SWAP,np.sqrt(0e6),jump_operator,density_mat,50e-9)
    final_state = TimeEvolution(H_SWAP,np.sqrt(0.1e6),jump_operator,density_mat,50e-9)
    
    print(ideal_state,density_mat)
    print( (1-(ideal_state*final_state).tr()),'ref:',(1-(ideal_state*ideal_state).tr()),'compare indentity',(1-(ideal_state*density_mat).tr()) )

    Error.append((1-(ideal_state*final_state).tr()))
    Ref_Error.append((1-(ideal_state*ideal_state).tr())  )
print(np.mean(Error))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[-2.46679227e-04+0.00000000e+00j  0.00000000e+00+5.16771247e-08j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00-5.16771247e-08j  9.99753321e-01+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = T

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 4.99876658e-01+0.0000000e+00j  0.00000000e+00-2.5838563e-08j
   4.99876658e-01+0.0000000e+00j  0.00000000e+00-2.5838563e-08j
   0.00000000e+00+0.0000000e+00j]
 [ 0.00000000e+00+2.5838563e-08j -1.23339613e-04+0.0000000e+00j
   0.00000000e+00+2.5838563e-08j -1.23339613e-04+0.0000000e+00j
   0.00000000e+00+0.0000000e+00j]
 [ 4.99876658e-01+0.0000000e+00j  0.00000000e+00-2.5838563e-08j
   4.99876658e-01+0.0000000e+00j  0.00000000e+00-2.5838563e-08j
   0.00000000e+00+0.0000000e+00j]
 [ 0.00000000e+00+2.5838563e-08j -1.23339613e-04+0.0000000e+00j
   0.00000000e+00+2.5838563e-08j -1.23339613e-04+0.0000000e+00j
   0.00000000e+00+0.0000000e+00j]
 [ 0.00000000e+00+0.0000000e+00j  0.00000000e+00+0.0000000e+00j
   0.00000000e+00+0.0000000e+00j  0.00000000e+00+0.0000000e+00j
   0.00000000e+00+0.0000000e+00j]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0. 

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[-1.23339613e-04+0.00000000e+00j  0.00000000e+00+2.58385634e-08j
   0.00000000e+00+1.23339613e-04j  2.58385634e-08+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00-2.58385634e-08j  4.99876656e-01+0.00000000e+00j
  -2.58385634e-08+0.00000000e+00j  0.00000000e+00-4.99876656e-01j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00-1.23339613e-04j -2.58385634e-08+0.00000000e+00j
  -1.23339613e-04+0.00000000e+00j  0.00000000e+00+2.58385634e-08j
   0.00000000e+00+0.00000000e+00j]
 [ 2.58385634e-08+0.00000000e+00j  0.00000000e+00+4.99876656e-01j
   0.00000000e+00-2.58385634e-08j  4.99876656e-01+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = T

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[-1.23339612e-04+0.00000000e+00j  0.00000000e+00+2.58385617e-08j
  -2.58385617e-08+0.00000000e+00j  0.00000000e+00-1.23339612e-04j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00-2.58385617e-08j  4.99876653e-01+0.00000000e+00j
   0.00000000e+00+4.99876653e-01j  2.58385617e-08+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [-2.58385617e-08+0.00000000e+00j  0.00000000e+00-4.99876653e-01j
   4.99876653e-01+0.00000000e+00j  0.00000000e+00-2.58385617e-08j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+1.23339612e-04j  2.58385617e-08+0.00000000e+00j
   0.00000000e+00+2.58385617e-08j -1.23339612e-04+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = T

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.24987668+0.j   0.        +0.25j 0.        +0.25j 0.24987668+0.j
  0.        +0.j  ]
 [0.        -0.25j 0.24987663+0.j   0.24987663+0.j   0.        -0.25j
  0.        +0.j  ]
 [0.        -0.25j 0.24987663+0.j   0.24987663+0.j   0.        -0.25j
  0.        +0.j  ]
 [0.24987668+0.j   0.        +0.25j 0.        +0.25j 0.24987668+0.j
  0.        +0.j  ]
 [0.        +0.j   0.        +0.j   0.        +0.j   0.        +0.j
  0.        +0.j  ]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.25+0.j   0.  -0.25j 0.  -0.25j 0.25+0.j   0.  +0.j  ]
 [0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.25j 0.  +0.j  ]
 [0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.25j 0.  +0.j  ]
 [0.25+0.j   0.  -0.25j 0.  -0.25j 0.25+0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]]
0.0007147998228187458 ref: 0.0004932630369578472 compare indentity 1.000246679223938

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.24987663+0.j   0.        -0.25j 0.24987663+0.j   0.        -0.25j
  0.        +0.j  ]
 [0.        +0.25j 0.24987668+0.j   0.        +0.25j 0.24987668+0.j
  0.        +0.j  ]
 [0.24987663+0.j   0.        -0.25j 0.24987663+0.j   0.        -0.25j
  0.        +0.j  ]
 [0.        +0.25j 0.24987668+0.j   0.        +0.25j 0.24987668+0.j
  0.        +0.j  ]
 [0.        +0.j   0.        +0.j   0.        +0.j   0.        +0.j
  0.        +0.j  ]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.25+0.j   0.  +0.25j 0.25+0.j   0.  +0.25j 0.  +0.j  ]
 [0.  -0.25j 0.25+0.j   0.  -0.25j 0.25+0.j   0.  +0.j  ]
 [0.25+0.j   0.  +0.25j 0.25+0.j   0.  +0.25j 0.  +0.j  ]
 [0.  -0.25j 0.25+0.j   0.  -0.25j 0.25+0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]]
0.0021500216153717 ref: 0.0004932632476173371 compare indentity 1.0002466792239153
Q

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.25+0.j   0.25+0.j   0.  -0.25j 0.  -0.25j 0.  +0.j  ]
 [0.25+0.j   0.25+0.j   0.  -0.25j 0.  -0.25j 0.  +0.j  ]
 [0.  +0.25j 0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.j  ]
 [0.  +0.25j 0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.25+0.j   0.25+0.j   0.  -0.25j 0.  -0.25j 0.  +0.j  ]
 [0.25+0.j   0.25+0.j   0.  -0.25j 0.  -0.25j 0.  +0.j  ]
 [0.  +0.25j 0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.j  ]
 [0.  +0.25j 0.  +0.25j 0.25+0.j   0.25+0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]]
0.0009365884423291337 ref: 3.5982376078713685e-08 compare indentity 1.7991188205890296e-08
Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.25  0.25 -0.25 -0.25  0.  ]
 [ 0.25  0.25 -0.25 -0.2

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.24987666+0.00000000e+00j -0.24987666+0.00000000e+00j
  -0.25      +2.58385638e-08j -0.25      +2.58385638e-08j
   0.        +0.00000000e+00j]
 [-0.24987666+0.00000000e+00j  0.24987666+0.00000000e+00j
   0.25      -2.58385638e-08j  0.25      -2.58385638e-08j
   0.        +0.00000000e+00j]
 [-0.25      -2.58385638e-08j  0.25      +2.58385638e-08j
   0.24987666+0.00000000e+00j  0.24987666+0.00000000e+00j
   0.        +0.00000000e+00j]
 [-0.25      -2.58385638e-08j  0.25      +2.58385638e-08j
   0.24987666+0.00000000e+00j  0.24987666+0.00000000e+00j
   0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j]] Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25  0.25  0.25  0.  ]
 [-0.25  0.25 -0.25 -0.25  0.  ]
 [ 0.25 -0.25  0.2

In [204]:
np.mean(np.array(Error)-np.array(Ref_Error))

0.0016303219177747426

In [227]:
np.mean(np.array(Error)-np.array(Ref_Error))*2

(0.0017175063195587334+0j)

In [211]:
#SWAP
Gamma11 = np.array([0.        +0.00000000e+00j, 0.        +0.00000000e+00j,
       0.00249379+0.00000000e+00j, 0.00249379+0.00000000e+00j,
       0.        +0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124729+0.00000000e+00j, 0.00249625+0.00000000e+00j,
       0.        +0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124729+0.00000000e+00j, 0.00249625+0.00000000e+00j,
       0.        +0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124729+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00090636+0.00000000e+00j,
       0.        +0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124729+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00407995+0.00000000e+00j,
       0.00045324+0.00000000e+00j, 0.00045323+0.00000000e+00j,
       0.00045324+0.00000000e+00j, 0.00204101+0.00000000e+00j,
       0.00204102+0.00000000e+00j, 0.00204101+0.00000000e+00j,
       0.00045323+0.00000000e+00j, 0.00204102+0.00000000e+00j,
       0.00204102+0.00000000e+00j, 0.00045323+0.00000000e+00j,
       0.00204102+0.00000000e+00j, 0.00045323+0.00000000e+00j,
       0.00204101+0.00000000e+00j, 0.00045323+0.00000000e+00j,
       0.00204101+0.00000000e+00j, 0.00045323+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124728+0.00000000e+00j,
       0.00124852+0.00000000e+00j, 0.00124852+0.00000000e+00j,
       0.00124729+0.00000000e+00j, 0.00124852-2.71050543e-20j,
       0.00124852+0.00000000e+00j, 0.00124729+0.00000000e+00j,
       0.00124852+2.71050543e-20j, 0.00124729+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124852+0.00000000e+00j,
       0.00124852+0.00000000e+00j, 0.00124729+0.00000000e+00j,
       0.00124728+0.00000000e+00j, 0.00124852+0.00000000e+00j])

#SWAP
Gamma11_01 = np.array([ 0.        ,  0.        ,  0.00137779,  0.00138032,  0.        ,
        0.00088906,  0.0008895 ,  0.00088905,  0.00088951,  0.00124844,
        0.        ,  0.00088906,  0.0008895 ,  0.00088905,  0.00088951,
        0.00124844,  0.        ,  0.00088906,  0.0008895 ,  0.00088906,
        0.0008895 ,  0.00296801,  0.        ,  0.00088906,  0.0008895 ,
        0.00088906,  0.0008895 , -0.00020991,  0.00165752,  0.00165751,
        0.00165752,  0.00019369,  0.00019369,  0.00019369,  0.00165751,
        0.00019369,  0.00019369,  0.00165751,  0.00019369,  0.00165751,
        0.00019369,  0.00165751,  0.00019369,  0.00165751,  0.00054576,
        0.00054576,  0.00093655,  0.00093656,  0.00054575,  0.00093655,
        0.00093656,  0.00054575,  0.00093655,  0.00054575,  0.00054576,
        0.00093656,  0.00093656,  0.00054575,  0.00054576,  0.00093655])

In [213]:
np.mean(Gamma11)*2*4

(0.009979110666666666+0j)

In [146]:
Error = []
for state in Total_60_extend:
    density_mat = qt.Qobj(state)*qt.Qobj(state).dag()
#     H_SWAP = 0.5*qt.Qobj([[1,0,0,0,0],[0,0,1,0,0],[0,1,0,0,0],[0,0,0,1,0],[0,0,0,0,1]])*10e6*2*np.pi
#     ideal_state = TimeEvolution(H_SWAP,np.sqrt(0e6),jump_operator,density_mat,50e-9)
#     final_state = TimeEvolution(H_SWAP,np.sqrt(1e6),jump_operator,density_mat,50e-9)
    
    final_state = Lt(jump_operator,density_mat)*0.001+density_mat
    ideal_state = density_mat
    
#     final_state  = (-1j*(H_SWAP*density_mat-density_mat*H_SWAP)+Lt(jump_operator,density_mat)*0.00).expm()*density_mat
#     ideal_state = (-1j*(H_SWAP*density_mat-density_mat*H_SWAP)).expm()*density_mat
    

    print( (1-(ideal_state*final_state).tr())/0.001 )

    Error.append((1-(ideal_state*final_state).tr())/0.001)
    
print(np.mean(Error))

0.0
0.0
0.0
1.0000000000000009
4.440892098500626e-13
4.440892098500626e-13
0.500000000000389
4.440892098500626e-13
0.500000000000389
0.500000000000389
4.440892098500626e-13
4.440892098500626e-13
0.500000000000389
4.440892098500626e-13
0.500000000000389
0.500000000000389
4.440892098500626e-13
4.440892098500626e-13
0.500000000000389
4.440892098500626e-13
0.500000000000389
0.500000000000389
4.440892098500626e-13
4.440892098500626e-13
0.500000000000389
4.440892098500626e-13
0.500000000000389
0.500000000000389
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.24999999999997247
0.2499999

In [144]:
for jj in range(60):
    state = Total_60_extend[jj]
    density_mat = qt.Qobj(state)*qt.Qobj(state).dag()
    Final_s = (Lt(jump_operator,density_mat)*0.01).expm()*density_mat

    for i in range(25500):
        A = np.matmul( cliffords.generate_2QB_Cliffords(i),Total_60[jj] )
        if np.abs(np.abs(np.array(A)[0][0]) - 1) <0.05:
            break    
    recover_oper = qt.Qobj( np.array(cliffords.generate_2QB_Cliffords(i)) )
    final_density = recover_oper*qt.Qobj(Final_s.full()[0:4,0:4])* recover_oper.dag()
    print( (1-final_density.full()[0][0])/0.01  )

NameError: name 'cliffords' is not defined

In [202]:
qt.Qobj( np.array(cliffords.generate_2QB_Cliffords(i)) )

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-1.23259516e-32+5.00000000e-01j  1.23259516e-32-5.00000000e-01j
  -5.00000000e-01+1.23259516e-32j  5.00000000e-01-1.23259516e-32j]
 [ 5.00000000e-01+1.23259516e-32j  5.00000000e-01+1.23259516e-32j
   1.23259516e-32+5.00000000e-01j  1.23259516e-32+5.00000000e-01j]
 [ 1.23259516e-32+5.00000000e-01j -1.23259516e-32-5.00000000e-01j
   5.00000000e-01+1.23259516e-32j -5.00000000e-01-1.23259516e-32j]
 [ 5.00000000e-01-1.23259516e-32j  5.00000000e-01-1.23259516e-32j
   1.23259516e-32-5.00000000e-01j  1.23259516e-32-5.00000000e-01j]]

In [194]:
Final_s

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[ 0.24968848+0.j         -0.24968848+0.j          0.        +0.24968848j
   0.        -0.24968848j  0.        +0.j        ]
 [-0.24968848+0.j          0.24968848+0.j          0.        -0.24968848j
   0.        +0.24968848j  0.        +0.j        ]
 [ 0.        -0.24968848j  0.        +0.24968848j  0.24968848+0.j
  -0.24968848+0.j          0.        +0.j        ]
 [ 0.        +0.24844004j  0.        -0.24844004j -0.24844004+0.j
   0.24844004+0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]]

In [ ]:
# swap 0.2
# swap 0.2
# swap 0.2
# swap 0.2
# swap 0.2
# leakage_101  0.25
# leakage_100  0.25
# leakage_001  0.25

In [188]:
density_mat.full()[0:4,0:4]

array([[ 0.25+0.j  , -0.25+0.j  ,  0.  +0.25j,  0.  -0.25j],
       [-0.25+0.j  ,  0.25+0.j  ,  0.  -0.25j,  0.  +0.25j],
       [ 0.  -0.25j,  0.  +0.25j,  0.25+0.j  , -0.25+0.j  ],
       [ 0.  +0.25j,  0.  -0.25j, -0.25+0.j  ,  0.25+0.j  ]])

In [113]:
3/16

0.1875

In [ ]:
for state in Total_60_extend:
    density_mat = qt.Qobj(state)*qt.Qobj(state).dag()
    A = (((Lt(jump_operator,density_mat)*0.01).expm()*density_mat)*density_mat)
    print(1-A.tr())

In [101]:
Lt(jump_operator,Total_60_extend[-1])

array([0. +0.j, 0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j])

## single qubit

In [232]:
A = np.zeros([2,2])
A[0,0]=1
A[1,1]=-1
jump_operator = qt.Qobj(A)
jump_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [235]:
States = [ (qt.basis(2,0)+qt.basis(2,1))/np.sqrt(2),
          (qt.basis(2,0)+1j*qt.basis(2,1))/np.sqrt(2),
          (qt.basis(2,0)-qt.basis(2,1))/np.sqrt(2),
          (qt.basis(2,0)-1j*qt.basis(2,1))/np.sqrt(2),
          qt.basis(2,0),
          qt.basis(2,1)]

In [236]:
Error = []
for state in States:
    density_mat = qt.Qobj(state)*qt.Qobj(state).dag()
    A = (((Lt(jump_operator,density_mat)*0.001).expm()*density_mat)*density_mat)
    
#     print( (1-A.tr())/0.001 )
#     print( Lt(jump_operator,density_mat) )
#     print(  (Lt(jump_operator,density_mat)*0.001).expm()*density_mat )
    Error.append((1-A.tr())/0.001)
    
print(np.mean(Error))

0.6663334444168741


## RB states

In [8]:
Four_32=np.array([[(0.5+0j), 0.5j, (0.5+0j), 0.5j],
[(0.5+0j), 0.5j, -0.5j, (0.5+0j)],
[(0.5+0j), 0.5j, (-0.5+0j), (-0-0.5j)],
[(0.5+0j), 0.5j, (0.5+0j), (-0-0.5j)],
[(0.5+0j), 0.5j, 0.5j, (0.5+0j)],
[(0.5+0j), 0.5j, (-0.5+0j), 0.5j],
[(0.5+0j), 0.5j, 0.5j, (-0.5+0j)],
[(0.5+0j), 0.5j, (-0-0.5j), (-0.5+0j)],
[(0.5+0j), (-0-0.5j), (-0-0.5j), (-0.5+0j)],
[(0.5+0j), (-0-0.5j), (-0.5+0j), (-0-0.5j)],
[(0.5+0j), (-0-0.5j), 0.5j, (0.5+0j)],
[(0.5+0j), -0.5j, (0.5+0j), 0.5j],
[(0.5+0j), -0.5j, (0.5+0j), -0.5j],
[(0.5+0j), (-0-0.5j), (-0-0.5j), (0.5+0j)],
[(0.5+0j), -0.5j, (-0.5+0j), 0.5j],
[(0.5+0j), -0.5j, 0.5j, (-0.5+0j)],
[(0.5+0j), (0.5+0j), (0.5+0j), (-0.5+0j)],
[(0.5+0j), (0.5+0j), (-0.5+0j), (0.5+0j)],
[(0.5+0j), (0.5+0j), -0.5j, (-0-0.5j)],
[(0.5+0j), (0.5+0j), (0.5+0j), (0.5+0j)],
[(0.5+0j), (0.5+0j), (-0-0.5j), 0.5j],
[(0.5+0j), (0.5+0j), 0.5j, 0.5j],
[(0.5+0j), (0.5+0j), (-0.5+0j), (-0.5+0j)],
[(0.5+0j), (0.5+0j), 0.5j, -0.5j],
[(0.5+0j), (-0.5+0j), 0.5j, (-0-0.5j)],
[(0.5+0j), (-0.5+0j), 0.5j, 0.5j],
[(0.5+0j), (-0.5+0j), (-0.5+0j), (-0.5+0j)],
[(0.5+0j), (-0.5+0j), (0.5+0j), (-0.5+0j)],
[(0.5+0j), (-0.5+0j), (-0.5+0j), (0.5+0j)],
[(0.5+0j), (-0.5+0j), -0.5j, (-0-0.5j)],
[(0.5+0j), (-0.5+0j), (0.5+0j), (0.5+0j)],
[(0.5+0j), (-0.5+0j), -0.5j, 0.5j]])


One_4 = np.array([[1,0j,0j,0j],[0j,1,0,0],[0j,0,1,0],[0j,0,0,1]])

TWO_24 = np.array([[1, 1, 0, 0],
 [1, 0, 1, 0],
 [1, 0, 0, 1],
 [0, 1, 1, 0],
 [0, 1, 0, 1],
 [0, 0, 1, 1],
 [1, -1, 0, 0],
 [1, 0, -1, 0],
 [1, 0, 0, -1],
 [0, 1, -1, 0],
 [0, 1, 0, -1],
 [0, 0, 1, -1],
 [1, 1j, 0, 0],
 [1, 0, 1j, 0],
 [1, 0, 0, 1j],
 [0, 1, 1j, 0],
 [0, 1, 0, 1j],
 [0, 0, 1, 1j],
 [1, (-0-1j), 0, 0],
 [1, 0, (-0-1j), 0],
 [1, 0, 0, (-0-1j)],
 [0, 1, (-0-1j), 0],
 [0, 1, 0, (-0-1j)],
 [0, 0, 1, (-0-1j)]])/np.sqrt(2)

Total_60 = np.append( np.append(One_4,TWO_24,axis=0),Four_32,axis=0  )

Total_60_extend = []
for i,arr in enumerate(Total_60):
    Total_60_extend.append(np.append(arr,0))
np.array(Total_60_extend)

array([[ 1.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         1.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ],
       [ 0.70710678+0.j        ,  0.70710678+0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.70710678+0.j        ,  0.        +0.j        ,
         0.70710678+0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.70710678+0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.707106

In [35]:
A*A.dag()

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.25+0.j   0.  -0.25j 0.25+0.j   0.  -0.25j]
 [0.  +0.25j 0.25+0.j   0.  +0.25j 0.25+0.j  ]
 [0.25+0.j   0.  -0.25j 0.25+0.j   0.  -0.25j]
 [0.  +0.25j 0.25+0.j   0.  +0.25j 0.25+0.j  ]]

In [148]:
import cliffords

In [150]:
Total_60[50]

array([ 0.5+0.j,  0.5+0.j, -0.5+0.j, -0.5+0.j])

In [149]:
cliffords.generate_2QB_Cliffords(100)

matrix([[-1.23259516e-32+5.00000000e-01j,
          1.23259516e-32-5.00000000e-01j,
         -1.23259516e-32-5.00000000e-01j,
          1.23259516e-32+5.00000000e-01j],
        [ 5.00000000e-01+1.23259516e-32j,
          5.00000000e-01+1.23259516e-32j,
         -5.00000000e-01+1.23259516e-32j,
         -5.00000000e-01+1.23259516e-32j],
        [ 5.00000000e-01-1.23259516e-32j,
         -5.00000000e-01+1.23259516e-32j,
          5.00000000e-01+1.23259516e-32j,
         -5.00000000e-01-1.23259516e-32j],
        [-1.23259516e-32-5.00000000e-01j,
         -1.23259516e-32-5.00000000e-01j,
          1.23259516e-32-5.00000000e-01j,
          1.23259516e-32-5.00000000e-01j]])

In [158]:
A = np.matmul( cliffords.generate_2QB_Cliffords(100),Total_60[50] )

In [179]:
for i in range(25500):
    A = np.matmul( cliffords.generate_2QB_Cliffords(i),Total_60[50] )
    if np.abs(np.abs(np.array(A)[0][0]) - 1) <0.05:
        print(i)
        print(A)
        break

124
[[ 1.00000000e+00+0.j  0.00000000e+00+0.j -2.46519033e-32+0.j
   0.00000000e+00+0.j]]


In [171]:
np.array(A)[0][0]

(0.5+0j)

In [180]:
cliffords.generate_2QB_Cliffords(124)

matrix([[ 5.00000000e-01+1.23259516e-32j,
          5.00000000e-01+1.23259516e-32j,
         -5.00000000e-01+1.23259516e-32j,
         -5.00000000e-01+1.23259516e-32j],
        [ 1.23259516e-32-5.00000000e-01j,
         -1.23259516e-32+5.00000000e-01j,
          1.23259516e-32+5.00000000e-01j,
         -1.23259516e-32-5.00000000e-01j],
        [-1.23259516e-32-5.00000000e-01j,
         -1.23259516e-32-5.00000000e-01j,
          1.23259516e-32-5.00000000e-01j,
          1.23259516e-32-5.00000000e-01j],
        [-5.00000000e-01+1.23259516e-32j,
          5.00000000e-01-1.23259516e-32j,
         -5.00000000e-01-1.23259516e-32j,
          5.00000000e-01+1.23259516e-32j]])