In [1]:
import sys
import numpy as np
import time
import matplotlib.pyplot as plt
from scipy import interpolate 
sys.path.append(r'C:\Chuji\Code_and_Data\MyCode')
sys.path.append(r'C:\Chuji\Code_and_Data\SourceCode\Labber_Drivers\Drivers\MultiQubit_PulseGenerator_Custom')
import Circuit_Simulator 
import PulseGenerator as PG
from toolfunc import *
from toolfunc.adia_analysis import *
from toolfunc.pulse_filter import *

In [2]:
import cliffords

In [3]:
import numpy as np
from numpy import matmul as mul
from numpy.linalg import inv as inv
from numpy.linalg import eig as eig
from numpy import tensordot as tensor
from numpy import dot
import random

In [4]:
cliffords.get_stabilizer(psi_00)

NameError: name 'psi_00' is not defined

In [ ]:
psi_00

In [ ]:
# help(cliffords.get_stabilizer)

In [ ]:
cliffords.

In [23]:
psi_00

matrix([[-5.00000000e-01-4.71844785e-16j],
        [ 7.49400542e-16-5.00000000e-01j],
        [ 2.77555756e-16-5.00000000e-01j],
        [-5.00000000e-01+3.60822483e-16j]])

In [44]:
psi_00 = np.matrix('1;0;0;0')
count_1=0
count_sqrt2=0
count_2=0
All_states=[]

for kk in range(3000):
#     psi_00 = np.matrix('1;0;0;0')
    for i in range(60):
        g = cliffords.generate_2QB_Cliffords(random.randint(0,11519))
        psi_00 = dot(g,psi_00)
    AA = np.sum(np.abs(psi_00))
#     print('kk',kk,'AA',AA)
    if abs(AA-1)<0.02:
        print('kk',kk,'AA',AA)
        count_1+=1
    elif abs(AA-2)<0.02:
        count_2+=1
    else:
        count_sqrt2+=1
    All_states.append(psi_00)

kk 7 AA 0.9999999999996866
kk 27 AA 0.9999999999988504
kk 41 AA 0.9999999999982722
kk 47 AA 0.9999999999980206
kk 83 AA 0.9999999999965313
kk 114 AA 0.999999999995251
kk 137 AA 0.9999999999943154
kk 142 AA 0.9999999999941145
kk 145 AA 0.9999999999939908
kk 150 AA 0.9999999999937879
kk 167 AA 0.9999999999930816
kk 184 AA 0.9999999999923614
kk 186 AA 0.9999999999922795
kk 187 AA 0.9999999999922385
kk 188 AA 0.9999999999921999
kk 239 AA 0.9999999999900978
kk 249 AA 0.9999999999896981
kk 257 AA 0.9999999999893767
kk 298 AA 0.9999999999876976
kk 305 AA 0.9999999999874069
kk 323 AA 0.9999999999866699
kk 327 AA 0.9999999999865081
kk 328 AA 0.9999999999864663
kk 329 AA 0.9999999999864251
kk 343 AA 0.9999999999858273
kk 346 AA 0.9999999999857064
kk 361 AA 0.9999999999850839
kk 362 AA 0.9999999999850439
kk 368 AA 0.9999999999847861
kk 371 AA 0.9999999999846628
kk 374 AA 0.9999999999845388
kk 422 AA 0.9999999999825757
kk 423 AA 0.9999999999825323
kk 470 AA 0.9999999999805695
kk 487 AA 0.999999999

In [45]:
count_1

213

In [46]:
count_2

1574

In [47]:
count_sqrt2

1213

In [48]:
np.array(All_states[0])[1][0]

(-0.49999999999997913+4.7537313482218424e-17j)

In [55]:
con=0
for state in All_states:
    if np.abs(np.abs(np.array( state )[3][0])-1)<0.1:
        con+=1
con

57

In [ ]:
49   54
29   53
43   49
68   57

In [ ]:
103
82
92


In [7]:
def reform_mat_arr(mat):
    y_arr=[]
    norm_factor =np.abs(complex(mat[0]))/complex(mat[0])
    for i,a in enumerate(mat):
        ac = complex(a)*norm_factor
        y = round(np.real(ac),4)+1j*round(np.imag(ac),4)
        y_arr.append(y)
    return y_arr

def reform_mat(mat):
    y_arr=0+0j
    
    if np.abs(complex(mat[0]))>0.1:
        norm_factor =np.abs(complex(mat[0]))/complex(mat[0])
    elif np.abs(complex(mat[1]))>0.1:
        norm_factor =np.abs(complex(mat[1]))/complex(mat[1])
    elif np.abs(complex(mat[2]))>0.1:
        norm_factor =np.abs(complex(mat[2]))/complex(mat[2])
    else:
        norm_factor =np.abs(complex(mat[3]))/complex(mat[3])
    
    for i,a in enumerate(mat):
        ac = complex(a)*norm_factor
        y = round(np.real(ac),2)+1j*round(np.imag(ac),2)
        y_arr += y*10**i
    return y_arr

In [8]:
New_states=[]
for aaa in All_states:
    New_states.append( reform_mat(aaa) )
    New_states.append( reform_mat(aaa)*-1 )
    New_states.append( reform_mat(aaa)*1j )
    New_states.append( reform_mat(aaa)*-1j )
set(New_states)

{(-1000+0j),
 (-781+0j),
 (-717.1+0j),
 (-710.71+0j),
 (-710-71j),
 (-710-7.1j),
 (-710-0.71j),
 (-710+0.71j),
 (-710+7.1j),
 (-710+71j),
 (-709.29+0j),
 (-702.9+0j),
 (-639+0j),
 (-555.5+0j),
 (-554.5+0j),
 (-550-5.5j),
 (-550-4.5j),
 (-550+4.5j),
 (-550+5.5j),
 (-545.5+0j),
 (-544.5+0j),
 (-505-50.5j),
 (-505-49.5j),
 (-505+49.5j),
 (-505+50.5j),
 (-500.5-55j),
 (-500.5-45j),
 (-500.5+45j),
 (-500.5+55j),
 (-499.5-55j),
 (-499.5-45j),
 (-499.5+45j),
 (-499.5+55j),
 (-495-50.5j),
 (-495-49.5j),
 (-495+49.5j),
 (-495+50.5j),
 (-455.5+0j),
 (-454.5+0j),
 (-450-5.5j),
 (-450-4.5j),
 (-450+4.5j),
 (-450+5.5j),
 (-445.5+0j),
 (-444.5+0j),
 (-100+0j),
 (-78.1+0j),
 (-71.71+0j),
 (-71-710j),
 (-71-7.1j),
 (-71-0.71j),
 (-71+0.71j),
 (-71+7.1j),
 (-71+710j),
 (-70.29+0j),
 (-63.9+0j),
 (-55-500.5j),
 (-55-499.5j),
 (-55+499.5j),
 (-55+500.5j),
 (-50.5-505j),
 (-50.5-495j),
 (-50.5+495j),
 (-50.5+505j),
 (-49.5-505j),
 (-49.5-495j),
 (-49.5+495j),
 (-49.5+505j),
 (-45-500.5j),
 (-45-499.5j),
 

In [10]:
len(set(New_states))/4

60.0

In [11]:
New_states_arr=[]
for aaa in All_states:
    New_states_arr.append(reform_mat_arr(aaa))

In [19]:
A=[]
for param in New_states_arr:
    if np.abs(np.sum(np.abs(param))-1.4)<0.1:
        A.append(param)

In [20]:
A

[[0j, (-0.4196+0.5691j), 0j, (0.5691+0.4196j)],
 [0j, (0.6748-0.2114j), 0j, (-0.6748+0.2114j)],
 [0j, 0j, (-0.0284+0.7065j), (0.7065+0.0284j)],
 [(0.7071+0j), (-0+0j), 0j, -0.7071j],
 [(0.7071+0j), (0.7071+0j), 0j, (-0+0j)],
 [0j, 0j, (0.5966-0.3796j), (0.5966-0.3796j)],
 [(0.7071+0j), 0j, 0j, (0.7071+0j)],
 [(0.7071+0j), 0j, 0j, (-0.7071+0j)],
 [(0.7071+0j), 0.7071j, 0j, 0j],
 [0j, 0j, (0.2276-0.6695j), (0.2276-0.6695j)],
 [(0.7071+0j), 0j, (-0-0.7071j), 0j],
 [(0.7071+0j), (-0+0j), (-0+0j), 0.7071j],
 [(0.7071+0j), (0.7071+0j), (-0+0j), (-0+0j)],
 [0j, (0.1243+0.6961j), 0j, (-0.6961+0.1243j)],
 [0j, 0j, (0.1042-0.6994j), (0.1042-0.6994j)],
 [(0.7071+0j), (0.7071+0j), 0j, (-0+0j)],
 [(0.7071+0j), 0j, 0j, (-0-0.7071j)],
 [(0.7071+0j), (0.7071+0j), 0j, (-0+0j)],
 [(0.7071+0j), 0.7071j, 0j, 0j],
 [0j, (-0+0j), (-0.6565+0.2626j), (-0.6565+0.2626j)],
 [(0.7071+0j), 0j, (-0.7071+0j), 0j],
 [0j, (0.6659-0.2378j), 0j, (-0.6659+0.2378j)],
 [(0.7071+0j), (0.7071+0j), 0j, 0j],
 [(0.7071+0j), -0.

In [14]:
A_set=[]
for param in A:
    if param not in A_set:
        A_set.append(param)

In [15]:
A_set

[[(0.5+0j), 0.5j, -0.5j, (-0.5+0j)],
 [(0.5+0j), (0.5+0j), (0.5+0j), (-0.5+0j)],
 [(0.5+0j), (-0-0.5j), 0.5j, (-0.5+0j)],
 [(0.5+0j), (0.5+0j), (0.5+0j), (0.5+0j)],
 [(0.5+0j), (-0.5+0j), (0.5+0j), (0.5+0j)],
 [(0.5+0j), (0.5+0j), -0.5j, 0.5j],
 [(0.5+0j), 0.5j, (-0.5+0j), 0.5j],
 [(0.5+0j), (-0-0.5j), (-0.5+0j), 0.5j],
 [(0.5+0j), 0.5j, (0.5+0j), (-0-0.5j)],
 [(0.5+0j), -0.5j, (-0.5+0j), -0.5j],
 [(0.5+0j), 0.5j, 0.5j, (-0.5+0j)],
 [(0.5+0j), 0.5j, (0.5+0j), 0.5j],
 [(0.5+0j), (0.5+0j), 0.5j, -0.5j],
 [(0.5+0j), (-0-0.5j), (-0-0.5j), (0.5+0j)],
 [(0.5+0j), (-0.5+0j), (-0.5+0j), (-0.5+0j)],
 [(0.5+0j), (-0-0.5j), 0.5j, (0.5+0j)],
 [(0.5+0j), (-0.5+0j), (0.5+0j), (-0.5+0j)],
 [(0.5+0j), (-0.5+0j), 0.5j, (-0-0.5j)],
 [(0.5+0j), 0.5j, (-0.5+0j), -0.5j],
 [(0.5+0j), -0.5j, (0.5+0j), (-0-0.5j)],
 [(0.5+0j), (-0.5+0j), (-0.5+0j), (0.5+0j)],
 [(0.5+0j), (-0-0.5j), (-0-0.5j), (-0.5+0j)],
 [(0.5+0j), (0.5+0j), -0.5j, (-0-0.5j)],
 [(0.5+0j), (-0.5+0j), -0.5j, 0.5j],
 [(0.5+0j), 0.5j, -0.5j, (0.5

In [ ]:
[(0.5+0j), 0.5j, 0.5, 0.5j],
[(0.5+0j), 0.5j, 0.5, -0.5j],
[(0.5+0j), 0.5j, -0.5, -0.5j],
[(0.5+0j), 0.5j, -0.5, 0.5j],
[(0.5+0j), 0.5j, 0.5j, 0.5],
[(0.5+0j), 0.5j, 0.5j, -0.5],
[(0.5+0j), 0.5j, -0.5j, -0.5],
[(0.5+0j), 0.5j, -0.5j, 0.5],


[(0.5+0j), -0.5j, 0.5, 0.5j],
[(0.5+0j), -0.5j, 0.5, -0.5j],
[(0.5+0j), -0.5j, -0.5, -0.5j],
[(0.5+0j), -0.5j, -0.5, 0.5j],
[(0.5+0j), -0.5j, 0.5j, (0.5+0j)],
[(0.5+0j), -0.5j, 0.5j, -0.5],
[(0.5+0j), -0.5j, -0.5j, 0.5],
[(0.5+0j), -0.5j, -0.5j, -0.5],


[(0.5+0j), (0.5+0j), (0.5+0j), (0.5+0j)],
[(0.5+0j), (0.5+0j), (0.5+0j), (-0.5+0j)],
[(0.5+0j), (0.5+0j), (-0.5+0j), (0.5+0j)],
[(0.5+0j), (0.5+0j), (-0.5+0j), (-0.5+0j)],
[(0.5+0j), (0.5+0j), 0.5j, 0.5j],
[(0.5+0j), (0.5+0j), 0.5j, -0.5j]
[(0.5+0j), (0.5+0j), (-0-0.5j), 0.5j],
[(0.5+0j), (0.5+0j), -0.5j, (-0-0.5j)],

[(0.5+0j), (-0.5+0j), (0.5+0j), (-0.5+0j)],
[(0.5+0j), (-0.5+0j), (0.5+0j), (0.5+0j)],
[(0.5+0j), (-0.5+0j), (-0.5+0j), (-0.5+0j)],
[(0.5+0j), (-0.5+0j), (-0.5+0j), (0.5+0j)],
[(0.5+0j), (-0.5+0j), 0.5j, (-0-0.5j)],
[(0.5+0j), (-0.5+0j), 0.5j, 0.5j],
[(0.5+0j), (-0.5+0j), -0.5j, (-0-0.5j)],
[(0.5+0j), (-0.5+0j), -0.5j, 0.5j],



In [26]:
3/16

0.1875

In [283]:
len(New_states)

12000

In [340]:
len(set(New_states))/4

120.0

In [329]:
set(New_states)

{(-0-10j),
 (-0-1j),
 (-0-444.5j),
 (-0-445.5j),
 (-0-455.5j),
 (-0-545.5j),
 (-0-63.9j),
 (-0-639j),
 (-0-7.81j),
 (-0-70.29j),
 (-0-702.9j),
 (-0-709.29j),
 (-0.71+0.71j),
 (-0.71+7.1j),
 (-0.71+710j),
 (-0.71+71j),
 (-0.71-0.71j),
 (-0.71-7.1j),
 (-0.71-710j),
 (-0.71-71j),
 (-1+0j),
 (-10+0j),
 (-100+0j),
 (-1000+0j),
 (-311.15+311.15j),
 (-311.15+318.85j),
 (-311.15+381.85j),
 (-311.15+388.15j),
 (-311.15-311.15j),
 (-311.15-318.85j),
 (-311.15-381.85j),
 (-311.15-388.15j),
 (-311.85+311.85j),
 (-311.85+318.15j),
 (-311.85+381.15j),
 (-311.85+388.85j),
 (-311.85-311.85j),
 (-311.85-318.15j),
 (-311.85-381.15j),
 (-311.85-388.85j),
 (-318.15+311.85j),
 (-318.15+318.15j),
 (-318.15+381.15j),
 (-318.15+388.85j),
 (-318.15-311.85j),
 (-318.15-318.15j),
 (-318.15-381.15j),
 (-318.15-388.85j),
 (-318.85+311.15j),
 (-318.85+318.85j),
 (-318.85+381.85j),
 (-318.85+388.15j),
 (-318.85-311.15j),
 (-318.85-318.85j),
 (-318.85-381.85j),
 (-318.85-388.15j),
 (-381.15+311.85j),
 (-381.15+318.15

In [290]:
count_1

206

In [291]:
count_2

1601

In [292]:
count_sqrt2

1193

In [186]:
float(np.abs(psi_00)[1])

0.49999999995868577

In [414]:
bin(int(6))[2:6].zfill(1)

'110'

In [418]:
gate_params_one=np.array([1,2,3,4])
T_r=3e-9
factor_r=-0.02
np.savetxt(r'C:\Chuji\Latex_Papers\Mypapers\ZZ_coupling_20210205\fig_zz\fig3_data\params_one_distor'+str(int(T_r*1e9))+'_'+str(factor_r)+'.txt',gate_params_one )

In [174]:
count_1

196

In [295]:
181+196+206
1584+1602+1601
1235+1202+1193

583

In [298]:
583/(4787+3630+583)*120

7.773333333333333

In [337]:
a=196+206
b=1602+1601
c=1202+1193

In [339]:
a/(a+b+c)*120

8.040000000000001

In [307]:
np.arange(-790e6,401e6,20e6)

array([-7.9e+08, -7.7e+08, -7.5e+08, -7.3e+08, -7.1e+08, -6.9e+08,
       -6.7e+08, -6.5e+08, -6.3e+08, -6.1e+08, -5.9e+08, -5.7e+08,
       -5.5e+08, -5.3e+08, -5.1e+08, -4.9e+08, -4.7e+08, -4.5e+08,
       -4.3e+08, -4.1e+08, -3.9e+08, -3.7e+08, -3.5e+08, -3.3e+08,
       -3.1e+08, -2.9e+08, -2.7e+08, -2.5e+08, -2.3e+08, -2.1e+08,
       -1.9e+08, -1.7e+08, -1.5e+08, -1.3e+08, -1.1e+08, -9.0e+07,
       -7.0e+07, -5.0e+07, -3.0e+07, -1.0e+07,  1.0e+07,  3.0e+07,
        5.0e+07,  7.0e+07,  9.0e+07,  1.1e+08,  1.3e+08,  1.5e+08,
        1.7e+08,  1.9e+08,  2.1e+08,  2.3e+08,  2.5e+08,  2.7e+08,
        2.9e+08,  3.1e+08,  3.3e+08,  3.5e+08,  3.7e+08,  3.9e+08])

In [ ]:
120种

In [ ]:
8+64+48

In [305]:
1-(2+np.sqrt(2))**2/16

0.27144660940672627

In [308]:
import qutip as qt

In [323]:
U = np.cos(np.pi/4)*qt.qeye(2)-1j*np.sin(np.pi/4)*qt.sigmax()
Ud = qt.tensor(U,U)
Ud.dims=[[4],[4]]

In [324]:
A = Ud*qt.basis(4)

In [327]:
A*A.dag()

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25+0.j    0.  +0.25j  0.  +0.25j -0.25+0.j  ]
 [ 0.  -0.25j  0.25+0.j    0.25+0.j    0.  +0.25j]
 [ 0.  -0.25j  0.25+0.j    0.25+0.j    0.  +0.25j]
 [-0.25+0.j    0.  -0.25j  0.  -0.25j  0.25+0.j  ]]

In [322]:
qt.basis(4)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]